spring:
  application:
    name: kopring-playground

  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true

blog:
  title: Blog
  banner:
    title: Warning
    content: The blog will be down tomorrow.